SRCS +=		./src/line_edition/vi_mode/alloc_vi.c				\
			./src/line_edition/vi_mode/getvi_keys.c				\
			./src/line_edition/vi_mode/setmode.c				\
			./src/line_edition/vi_mode/vi_command.c				\
			./src/line_edition/vi_mode/vi_edition.c				\
			./src/line_edition/coordinates_calc.c				\
			./src/line_edition/vi_mode/jump_occur.c				\
			./src/line_edition/vi_mode/vi_cdel.c				\
			./src/line_edition/vi_mode/vi_com_motion.c			\
			./src/line_edition/vi_mode/vi_delete.c				\
			./src/line_edition/vi_mode/vi_history.c				\
			./src/line_edition/vi_mode/vi_insert.c				\
			./src/line_edition/vi_mode/vi_paste.c				\
			./src/line_edition/vi_mode/vi_repeat.c				\
			./src/line_edition/vi_mode/vi_undo.c				\
			./src/line_edition/vi_mode/vi_visual.c				\
			./src/line_edition/vi_mode/vi_yank.c				\
			./src/line_edition/vi_mode/jump_vi_manager.c	\
			./src/line_edition/cpy.c							\
			./src/line_edition/cursor_motion.c					\
			./src/line_edition/del_env.c						\
			./src/line_edition/get_keys.c						\
			./src/line_edition/history.c						\
			./src/line_edition/isalt.c							\
			./src/line_edition/jump_words.c						\
			./src/line_edition/line_alloc.c						\
			./src/line_edition/line_edition.c					\
			./src/line_edition/line_read_notty.c				\
			./src/line_edition/line_read.c						\
			./src/line_edition/print_line.c						\
			./src/line_edition/reset_cursor.c					\
			./src/line_edition/term_manager.c					\
			./src/line_edition/termcaps.c
